# Generated by Django 5.2.3 on 2025-06-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=10, unique=True)),
                ('credit', models.IntegerField(max_length=1)),
            ],
        ),
    ]
