# Generated by Django 5.2.3 on 2025-06-21 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0004_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enr_date', models.DateField()),
                ('enr_status', models.BooleanField(default=True)),
                ('courseId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.course')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app0.registration')),
            ],
        ),
    ]
