# Generated by Django 5.2.3 on 2025-06-21 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0005_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='instructorId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app0.instructor'),
            preserve_default=False,
        ),
    ]
