# Generated by Django 5.2.3 on 2025-06-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0006_enrollment_instructorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(unique=True),
        ),
    ]
