# Generated by Django 5.2.3 on 2025-06-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0008_registration_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='name',
            new_name='instructor_name',
        ),
    ]
