# Generated by Django 5.2.3 on 2025-06-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0009_rename_name_instructor_instructor_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='instructor_name',
            new_name='name',
        ),
    ]
