# Generated by Django 5.2.3 on 2025-06-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0010_rename_instructor_name_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_code',
            field=models.CharField(default='No code', max_length=10),
        ),
        migrations.AddField(
            model_name='course',
            name='course_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_email',
            field=models.EmailField(default='nothing@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='instructor',
            name='instructor_phone',
            field=models.CharField(default='777777777', max_length=9),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
