# Generated by Django 5.2.3 on 2025-06-25 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app0', '0011_course_course_code_course_course_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('response', models.TextField()),
            ],
        ),
    ]
