# Generated by Django 5.2.3 on 2025-07-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_cartitem_quantity_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='images/default2.jpg', upload_to='images/'),
        ),
    ]
